import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import { cn } from "@/lib/utils";
import Footer from "@/components/layouts/Footer";
import MaxWidthWrapper from "@/components/layouts/MaxWidthWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cine Comodoro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn("relative h-full font-sans antialiased", inter.className)}
      >
        <MaxWidthWrapper>
          <Navbar />
          {children}
        </MaxWidthWrapper>
        <Footer />
      </body>
    </html>
  );
}
